- name: install swiftonfile dependencies
  yum: name={{ item }} state=present
  with_items:
    - git
    - python-pip

- name: check if swiftonfile is already cloned
  stat: path={{ source_dir }}/swiftonfile
  register: swiftonfile_cloned

- name: git clone swiftonfile
  git: repo=https://github.com/stackforge/swiftonfile.git dest={{ source_dir }}/swiftonfile accept_hostkey=yes
  when: not swiftonfile_cloned.stat.exists

- name: build a development installation of swiftonfile
  command: python setup.py install chdir={{ source_dir }}/swiftonfile
